# Site settings
title: Apoena Vision Lab
description: "Lab of Computer Vision Specialists."
baseurl: "/lab" # the subpath of your site, e.g. /blog
url: "https://apoenavision.github.io" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Apoena Vision Lab
    hero_description: "Lab of Computer Vision Specialists."

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 932 50 540
    emergency: 931 53 234
    email: apoenavision@gmail.com
    address: Manoel de Medeiros, s/n. <br> Dois Irmaos, Recife - Brazil <br> Zip-code: 52171-900

# Map
map:
    zoom: 17
    address: "R. Manuel de Medeiros, s/n.<br> Dois Irmãos, Recife - PE, Brazil<br> Zip-code: 52171-900"
    address_details: svg/min/logo.svg

# Social settings
instagram: http://instagram.com
youtube: http://youtube.com
feed: yes

# Footer
copyright: © 2019 Apoena Vision - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
